spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssz-service-product?autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: ssz1314..
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  application-id: ssz-service-product
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace:
      username: ""
      password: ""
  service:
    vgroup-mapping:
      my_test_tx_group: default
