seata:
  enabled: true
  application-id: ssz-api
  tx-service-group: ssz-api-group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.237.129:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.237.129:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      ssz-api-group: default