spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.237.129:3306/ssz-service-user?autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  application-id: ssz-service-user
  tx-service-group: ssz-service-user-group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.168.237.129:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.237.129:8848
      group : "SEATA_GROUP"
      namespace:
      username: ""
      password: ""
  service:
    vgroup-mapping:
      my_test_tx_group: default

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
      field-strategy: not-empty
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
