spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssz-service-user?autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password: ssz1314..
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  application-id: ssz-service-user
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace:
      username: ""
      password: ""
  service:
    vgroup-mapping:
      my_test_tx_group: default

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
      field-strategy: not-empty
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  max-total: 5000
  max-idle: 100
  min-idle: 50
  database: 11